---
title: "{{< var course.title >}} Schedule"
---

**Note**: The timeline of topics and assignments might be updated throughout the semester. 

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(googlesheets4)
library(gt)
library(tidyverse)
gs4_deauth()
d <- read_sheet("https://docs.google.com/spreadsheets/d/11-GEnoCxVbhQ_Fp48EvoRzhJGWVnUU7FW6cNvC2fnDI/edit?usp=sharing")
```

```{r, echo = FALSE}
d %>% 
  mutate(
    date = as.Date(date),
    day = ifelse(is.na(day), "", day),
    topic = ifelse(is.na(topic),"",topic)) %>%
  select(-admin_notes) |>
  rename(Day = day, Date = date, Topic = topic,Notes = notes,
         Exercises = exercises, Lab = Lab, Homework = HW) |>
  
  gt() %>%
  text_transform(cells_body(columns = c(Notes)),
                 fn = function(x){
                   ifelse(is.na(x), fontawesome::fa('laptop', fill_opacity = 0.1), 
                          glue::glue("<a href = {x}>{fontawesome::fa('laptop')}</a>"))
                 }) %>%
  text_transform(cells_body(columns = c(Exercises)),
                 fn = function(x){
                   ifelse(is.na(x), fontawesome::fa('users', fill_opacity = 0.1),
                          glue::glue("<a href = {x}>{fontawesome::fa('users')}</a>"))
                   
                 }) %>%
  text_transform(cells_body(columns = c(Homework)),
                 fn = function(x){
                   ifelse(is.na(x), fontawesome::fa('sticky-note', fill_opacity = 0.1), 
                          glue::glue("<a href = {x}>{fontawesome::fa('sticky-note')}</a>"))
                   
                 }) %>%
  text_transform(cells_body(columns = c(Lab)),
                 fn = function(x){
                   ifelse(is.na(x), fontawesome::fa('file-alt', fill_opacity = 0.1), 
                          glue::glue("<a href = {x}>{fontawesome::fa('flask')}</a>"))
                 }) %>%
  fmt_date(Date, date_style = 9) %>%
  sub_missing(columns = Date, missing_text = "")
```
